apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1
        image: {{ .Values.demo.image }}
        ports:
        - containerPort: 80